#include "defs.hpp"

int Block::counter=0;

//vector<Transaction*>  txns is best as it uses the & which is the same reference
Block::Block(ld timestamp, Block* parentBlock, Peer* miner, vector<Transaction*> &txns) 
    : timestamp(timestamp), parentBlock(parentBlock), miner(miner), txns(txns) {
    ID = counter++;
    size = computeSize();
    depth = computeDepth();
}

int Block::computeSize() { 
    int totalSize = 0;
    for (Transaction* txn : txns) {
        totalSize += txn->size;
    }
    return totalSize;
}

int Block::computeDepth() {  
    return (parentBlock == nullptr) ? 0 : parentBlock->depth + 1;
}

Block* Block::make_copy_for_peer(Peer* other) {
    // miner is himself but we have to add in blockchain of the node 
    // that is ok the node of blockchain
    Block* newBlock = new Block(timestamp, nullptr, miner, txns);
    Block* parent_block_in_other = nullptr; 

    if (parentBlock != nullptr) {
        // this pointer may be not in the current_block it is finding the
        // block* from the blockchain upon seeing into his chain
        // so it is easy to circulate and make copy for the
        // other peer same block generated by other miner
        parent_block_in_other = other->block_map[parentBlock->ID];  
    }

    newBlock->ID = ID;
    newBlock->size = size;
    newBlock->parentBlock = parent_block_in_other;
    newBlock->depth = newBlock->computeDepth();
    
    return newBlock;
}
